
touch "Oddział Chorób Wewnętrznych I i Gastroenterologii"
touch "Oddział Chorób Wewnętrznych II"
touch "Oddział Chirurgii Ogólnej i Naczyniowej"
touch "Oddział Chirurgii Ogólnej i Przewodu Pokarmowego"
touch "Oddział Anestezjologii i Intensywnej Terapii"
touch "Oddział Urologiczny"
touch "Oddział Neurologiczny z Pododdziałem Udarowym"
touch "Oddział Otolaryngologiczny"
touch "Oddział Urazowo-Ortopedyczny"
touch "Oddział Kardiologiczny"
touch "Oddział Okulistyczny"
touch "Oddział Chirurgii Szczękowo-Twarzowej"
touch "Oddział Reumatologiczny"
touch "Oddział Neurochirurgiczny"
touch "Oddział Nefrologiczny ze Stacją Dializ"
touch "Szpitalny Oddział Ratunkowy"
touch "Oddział Rehabilitacyjny"
touch "Oddział Rehabilitacji Dziecięcej - Dzienny Pobyt"
touch "Oddział Chirurgii i Traumatologii Dziecięcej"
touch "Oddział Gastroenterologii Dziecięcej"
touch "Oddział Chorób Dziecięcych"
touch "Oddział Położniczo - Ginekologiczny i Ginekologii Onkologicznej"
touch "Oddział Patologii i Intensywnej Terapii Noworodka"
touch "Oddział Obserwacyjno-Zakaźny"
touch "Oddział Psychiatryczny"
